# Generated by Django 5.1.2 on 2024-10-10 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ankle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_count', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Jump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lunge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.FloatField()),
                ('speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Squat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AnkleLeftSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtalar_angle_avg', models.FloatField()),
                ('angle_avg', models.FloatField()),
                ('subtalar_angle_std', models.FloatField()),
                ('angle_std', models.FloatField()),
                ('ankle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='left_side', to='core.ankle')),
            ],
        ),
        migrations.CreateModel(
            name='AnkleRightSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtalar_angle_avg', models.FloatField()),
                ('angle_avg', models.FloatField()),
                ('subtalar_angle_std', models.FloatField()),
                ('angle_std', models.FloatField()),
                ('ankle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='right_side', to='core.ankle')),
            ],
        ),
        migrations.CreateModel(
            name='GaitPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.FloatField()),
                ('exercise_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gait_phases', to='core.exerciseunit')),
            ],
        ),
        migrations.AddField(
            model_name='ankle',
            name='gait_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ankle', to='core.gaitphase'),
        ),
        migrations.CreateModel(
            name='Hip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gait_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hip', to='core.gaitphase')),
            ],
        ),
        migrations.CreateModel(
            name='HipLeftSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flexion_avg', models.FloatField()),
                ('adduction_avg', models.FloatField()),
                ('rotation_avg', models.FloatField()),
                ('flexion_std', models.FloatField()),
                ('adduction_std', models.FloatField()),
                ('rotation_std', models.FloatField()),
                ('hip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='left_side', to='core.hip')),
            ],
        ),
        migrations.CreateModel(
            name='HipRightSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flexion_avg', models.FloatField()),
                ('adduction_avg', models.FloatField()),
                ('rotation_avg', models.FloatField()),
                ('flexion_std', models.FloatField()),
                ('adduction_std', models.FloatField()),
                ('rotation_std', models.FloatField()),
                ('hip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='right_side', to='core.hip')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseunit',
            name='jump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_units', to='core.jump'),
        ),
        migrations.CreateModel(
            name='Knee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gait_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knee', to='core.gaitphase')),
            ],
        ),
        migrations.CreateModel(
            name='KneeLeftSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle_avg', models.FloatField()),
                ('angle_std', models.FloatField()),
                ('knee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='left_side', to='core.knee')),
            ],
        ),
        migrations.CreateModel(
            name='KneeRightSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle_avg', models.FloatField()),
                ('angle_std', models.FloatField()),
                ('knee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='right_side', to='core.knee')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseunit',
            name='land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_units', to='core.land'),
        ),
        migrations.CreateModel(
            name='LateralGastrocnemius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gait_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateral_gastrocnemius', to='core.gaitphase')),
            ],
        ),
        migrations.CreateModel(
            name='LateralGastrocnemiusLeftSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_avg', models.FloatField()),
                ('force_std', models.FloatField()),
                ('lateral_gastrocnemius', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='left_side', to='core.lateralgastrocnemius')),
            ],
        ),
        migrations.CreateModel(
            name='LateralGastrocnemiusRightSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_avg', models.FloatField()),
                ('force_std', models.FloatField()),
                ('lateral_gastrocnemius', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='right_side', to='core.lateralgastrocnemius')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseunit',
            name='lunge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_units', to='core.lunge'),
        ),
        migrations.CreateModel(
            name='MedialGastrocnemius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gait_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medial_gastrocnemius', to='core.gaitphase')),
            ],
        ),
        migrations.CreateModel(
            name='MedialGastrocnemiusLeftSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_avg', models.FloatField()),
                ('force_std', models.FloatField()),
                ('medial_gastrocnemius', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='left_side', to='core.medialgastrocnemius')),
            ],
        ),
        migrations.CreateModel(
            name='MedialGastrocnemiusRightSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_avg', models.FloatField()),
                ('force_std', models.FloatField()),
                ('medial_gastrocnemius', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='right_side', to='core.medialgastrocnemius')),
            ],
        ),
        migrations.CreateModel(
            name='Pelvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gait_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelvis', to='core.gaitphase')),
            ],
        ),
        migrations.CreateModel(
            name='PelvisLeftSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilt_angle_avg', models.FloatField()),
                ('list_angle_avg', models.FloatField()),
                ('rotation_angle_avg', models.FloatField()),
                ('tilt_angle_std', models.FloatField()),
                ('list_angle_std', models.FloatField()),
                ('rotation_angle_std', models.FloatField()),
                ('pelvis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='left_side', to='core.pelvis')),
            ],
        ),
        migrations.CreateModel(
            name='PelvisRightSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilt_angle_avg', models.FloatField()),
                ('list_angle_avg', models.FloatField()),
                ('rotation_angle_avg', models.FloatField()),
                ('tilt_angle_std', models.FloatField()),
                ('list_angle_std', models.FloatField()),
                ('rotation_angle_std', models.FloatField()),
                ('pelvis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='right_side', to='core.pelvis')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseunit',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_units', to='core.run'),
        ),
        migrations.CreateModel(
            name='Soleus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gait_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soleus', to='core.gaitphase')),
            ],
        ),
        migrations.CreateModel(
            name='SoleusLeftSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_avg', models.FloatField()),
                ('force_std', models.FloatField()),
                ('soleus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='left_side', to='core.soleus')),
            ],
        ),
        migrations.CreateModel(
            name='SoleusRightSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_avg', models.FloatField()),
                ('force_std', models.FloatField()),
                ('soleus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='right_side', to='core.soleus')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseunit',
            name='squat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_units', to='core.squat'),
        ),
        migrations.CreateModel(
            name='TibialisAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gait_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tibialis_anterior', to='core.gaitphase')),
            ],
        ),
        migrations.CreateModel(
            name='TibialisAnteriorLeftSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_avg', models.FloatField()),
                ('force_std', models.FloatField()),
                ('tibialis_anterior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='left_side', to='core.tibialisanterior')),
            ],
        ),
        migrations.CreateModel(
            name='TibialisAnteriorRightSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_avg', models.FloatField()),
                ('force_std', models.FloatField()),
                ('tibialis_anterior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='right_side', to='core.tibialisanterior')),
            ],
        ),
        migrations.AddField(
            model_name='squat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_squats', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='run',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_runs', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='lunge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lunges', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='land',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lands', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='jump',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jumps', to='core.userprofile'),
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.FloatField()),
                ('speed', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_walks', to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseunit',
            name='walk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_units', to='core.walk'),
        ),
    ]
