# Generated by Django 5.1.2 on 2024-10-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jump',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='land',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lunge',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='run',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='squat',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='walk',
            name='duration',
        ),
    ]
