# Generated by Django 5.1.2 on 2024-10-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_jump_duration_remove_land_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseunit',
            name='unit_count',
        ),
    ]
