# Generated by Django 5.1.2 on 2024-10-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ankleleftside_angle_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankle',
            name='gait_phase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ankle', to='core.gaitphase'),
        ),
        migrations.AlterField(
            model_name='hip',
            name='gait_phase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hip', to='core.gaitphase'),
        ),
        migrations.AlterField(
            model_name='knee',
            name='gait_phase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knee', to='core.gaitphase'),
        ),
        migrations.AlterField(
            model_name='lateralgastrocnemius',
            name='gait_phase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lateral_gastrocnemius', to='core.gaitphase'),
        ),
        migrations.AlterField(
            model_name='medialgastrocnemius',
            name='gait_phase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medial_gastrocnemius', to='core.gaitphase'),
        ),
        migrations.AlterField(
            model_name='pelvis',
            name='gait_phase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pelvis', to='core.gaitphase'),
        ),
        migrations.AlterField(
            model_name='soleus',
            name='gait_phase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soleus', to='core.gaitphase'),
        ),
        migrations.AlterField(
            model_name='tibialisanterior',
            name='gait_phase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tibialis_anterior', to='core.gaitphase'),
        ),
    ]
