# Generated by Django 5.1.2 on 2024-10-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ankle_gait_phase_alter_hip_gait_phase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='run',
            name='speed',
        ),
        migrations.AddField(
            model_name='exerciseunit',
            name='speed',
            field=models.FloatField(null=True),
        ),
    ]
